# Generated by Django 4.2.6 on 2023-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumScanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('medical_history', models.TextField()),
            ],
        ),
    ]
