# Generated by Django 4.2.5 on 2023-09-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCNN', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x7eff93a6d280>', max_length=200),
        ),
    ]
